"""SQLite persistence for request logs.

Single table, fixed schema, append-only. We keep it deliberately small:

    request_log(
        request_id  TEXT PRIMARY KEY,   -- uuid hex, generated by service
        session_id  TEXT,               -- nullable; client-provided
        ts          REAL NOT NULL,      -- unix time
        event       TEXT NOT NULL,      -- ask.start / ask.refuse / ask.complete
        question    TEXT,               -- already PII-redacted
        answer      TEXT,               -- already PII-redacted
        refused     INTEGER,            -- 0/1
        retrieval_count INTEGER,
        retrieval_ms REAL,
        generation_ms REAL,
        latency_ms  REAL,
        model       TEXT,
        meta        TEXT                -- JSON blob for forward-compat
    )

SQLite is the right tool here: one writer, one process, no concurrency
headaches. If we ever scale to multiple workers, swap to Postgres — the
schema is portable.
"""
from __future__ import annotations

import json
import sqlite3
import threading
from pathlib import Path

from app.config import get_settings

_lock = threading.Lock()
_conn_cache: dict[str, sqlite3.Connection] = {}

_SCHEMA = """
CREATE TABLE IF NOT EXISTS request_log (
    request_id      TEXT PRIMARY KEY,
    session_id      TEXT,
    ts              REAL NOT NULL,
    event           TEXT NOT NULL,
    question        TEXT,
    answer          TEXT,
    refused         INTEGER,
    retrieval_count INTEGER,
    retrieval_ms    REAL,
    generation_ms   REAL,
    latency_ms      REAL,
    model           TEXT,
    meta            TEXT
);
CREATE INDEX IF NOT EXISTS request_log_ts ON request_log(ts);
CREATE INDEX IF NOT EXISTS request_log_event ON request_log(event);
"""


def _get_conn() -> sqlite3.Connection:
    """Return a per-thread cached connection, creating the schema on first use.

    `check_same_thread=False` because FastAPI runs the handler in a worker
    thread; the lock guards concurrent writes from the same process.
    """
    settings = get_settings()
    path = settings.sqlite_path
    key = f"{path}::{threading.get_ident()}"
    if key not in _conn_cache:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(path, check_same_thread=False)
        conn.executescript(_SCHEMA)
        conn.commit()
        _conn_cache[key] = conn
    return _conn_cache[key]


def write_log(
    *,
    request_id: str,
    event: str,
    session_id: str | None = None,
    question: str | None = None,
    answer: str | None = None,
    refused: bool | None = None,
    retrieval_count: int | None = None,
    retrieval_ms: float | None = None,
    generation_ms: float | None = None,
    latency_ms: float | None = None,
    model: str | None = None,
    meta: dict | None = None,
    ts: float | None = None,
) -> None:
    """Insert one event row. All fields beyond the required ones are optional."""
    import time as _t

    with _lock:
        conn = _get_conn()
        conn.execute(
            """
            INSERT OR REPLACE INTO request_log
              (request_id, session_id, ts, event, question, answer, refused,
               retrieval_count, retrieval_ms, generation_ms, latency_ms,
               model, meta)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                request_id,
                session_id,
                ts if ts is not None else _t.time(),
                event,
                question,
                answer,
                None if refused is None else (1 if refused else 0),
                retrieval_count,
                retrieval_ms,
                generation_ms,
                latency_ms,
                model,
                json.dumps(meta or {}, ensure_ascii=False),
            ),
        )
        conn.commit()


def query_events(event: str | None = None, limit: int = 100) -> list[dict]:
    """Return the most recent rows, optionally filtered by event name."""
    conn = _get_conn()
    if event:
        cur = conn.execute(
            "SELECT * FROM request_log WHERE event = ? ORDER BY ts DESC LIMIT ?",
            (event, limit),
        )
    else:
        cur = conn.execute(
            "SELECT * FROM request_log ORDER BY ts DESC LIMIT ?", (limit,)
        )
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, row)) for row in cur.fetchall()]


def close_all() -> None:
    """Close all cached connections; used by tests."""
    with _lock:
        for conn in _conn_cache.values():
            conn.close()
        _conn_cache.clear()
